### ISSUE TITLE
error in ./run.sh

### ISSUE THREAD

**Issue by ohadianoush** [kan-bayashi/ParallelWaveGAN#51] opened 2020-01-16 10:43 UTC
by runing ./run.sh i get this error:

```
[Parallel(n_jobs=16)]: Done 6018 tasks      | elapsed:  2.4min
[Parallel(n_jobs=16)]: Done 7168 tasks      | elapsed:  2.7min
/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 608, in __call__
    return self.func(*args, **kwargs)
  File "/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/bahram/ParallelWaveGAN/parallel_wavegan/bin/preprocess.py", line 178, in _process_single_file
    write_hdf5(os.path.join(args.dumpdir, f"{utt_id}.h5"), "wave", audio.astype(np.float32))
  File "/home/bahram/ParallelWaveGAN/parallel_wavegan/utils/utils.py", line 87, in write_hdf5
    hdf5_file = h5py.File(hdf5_name, "r+")
  File "/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/h5py/_hl/files.py", line 175, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (bad object header version number)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bahram/ParallelWaveGAN/tools/venv/bin/parallel-wavegan-preprocess", line 11, in <module>
    load_entry_point('parallel-wavegan', 'console_scripts', 'parallel-wavegan-preprocess')()
  File "/home/bahram/ParallelWaveGAN/parallel_wavegan/bin/preprocess.py", line 190, in main
    [delayed(_process_single_file)(data) for data in tqdm(dataset)])
  File "/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
OSError: Unable to open file (bad object header version number)
# Accounting: time=404 threads=1
```

**Comment by kan-bayashi** [comment] 2020-01-16 10:55
It seems h5py (hdf5) issue.
Please provide your environment information.

OS (via uname -a): 
Python version:
h5py version:

**Comment by kan-bayashi** [comment] 2020-01-16 11:02
I'm not sure the warning is related to the issue, but at first please try to suppress the warning by installing psutil.
```
UserWarning: Failed to kill subprocesses on this platform. Please install psutil: https://github.com/giampaolo/psutil
```

**Comment by ohadianoush** [comment] 2020-01-19 06:59
> It seems h5py (hdf5) issue.
> Please provide your environment information.
> 
> OS (via `uname -a`):
> Python version:
> h5py version:
> 
> And which recipe did you try?

hi,
4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
----
by python command :
Python 2.7.15+
and
by phyton3 command:
Python 3.6.8
---
in python3:
>>> h5py.__version__
'2.10.0'

**Comment by ohadianoush** [comment] 2020-01-19 07:07
after installing psutil, i run it again and :

train_nodev/preprocessing.log

...
[Parallel(n_jobs=16)]: Done 4018 tasks      | elapsed:  1.6min
[Parallel(n_jobs=16)]: Done 4968 tasks      | elapsed:  2.0min
[Parallel(n_jobs=16)]: Done 6018 tasks      | elapsed:  2.3min
[Parallel(n_jobs=16)]: Done 7168 tasks      | elapsed:  2.7min
Exception in thread QueueManagerThread:
Traceback (most recent call last):
  File "/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/joblib/externals/loky/backend/utils.py", line 33, in _recursive_terminate_with_psutil
    children = psutil.Process(process.pid).children(recursive=True)
AttributeError: module 'psutil' has no attribute 'Process'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 747, in _queue_management_worker
    recursive_terminate(p)
  File "/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/joblib/externals/loky/backend/utils.py", line 26, in recursive_terminate
    _recursive_terminate_with_psutil(process)
  File "/home/bahram/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/joblib/externals/loky/backend/utils.py", line 34, in _recursive_terminate_with_psutil
    except psutil.NoSuchProcess:
AttributeError: module 'psutil' has no attribute 'NoSuchProcess'

WARNING:root:Dataset in hdf5 file already exists. recreate dataset in hdf5.


Now this is 2 days my command line stop :
./run.sh
Stage -1: Data download
Already exists. Skipped.
Stage 0: Data preparation
Successfully prepared data.
Stage 1: Feature extraction
Feature extraction start. See the progress via dump/dev/raw/preprocessing.log.
Feature extraction start. See the progress via dump/train_nodev/raw/preprocessing.log.
Feature extraction start. See the progress via dump/eval/raw/preprocessing.log.
Successfully finished feature extraction of dev set.
Successfully finished feature extraction of eval set.

without error or some thing else !!!

**Comment by kan-bayashi** [comment] 2020-01-19 23:15
> AttributeError: module 'psutil' has no attribute 'Process'

It seems that psutil is not yet successfully installed.
Could you try with virtualenv installation?
https://github.com/kan-bayashi/ParallelWaveGAN/blob/master/README.md#b-make-virtualenv

**Comment by ohadianoush** [comment] 2020-01-29 08:43
> > It seems h5py (hdf5) issue.
> > Please provide your environment information.
> > OS (via `uname -a`):
> > Python version:
> > h5py version:
> > And which recipe did you try?
> 
this one:ljspeech

**Comment by kan-bayashi** [comment] 2020-02-14 03:35
I could not reproduce this issue.
I will close this issue.

**Closed by kan-bayashi** 2020-02-14 03:35 UTC
Labels: bug
