### ISSUE TITLE
Cannot use WaveGAN with Glow-TTS and Nivida's Tacotron2

### ISSUE THREAD

**Issue by Charlottecuc** [kan-bayashi/ParallelWaveGAN#169] opened 2020-06-23 08:27 UTC
Hi. I trained the tacotron2 model (https://github.com/NVIDIA/tacotron2) and Glow-TTS model (https://github.com/jaywalnut310/glow-tts) by using the LJ speech dataset and can successfully synthesize voice by using WaveGlow as vocoder. 
However, when I turned to the Parallel WaveGan,  the synthzised waveform is quite strange:
![Screenshot 2020-06-23 at 4 24 30 PM](https://user-images.githubusercontent.com/43811904/85379190-10bbe200-b56e-11ea-8620-4e62a5df624a.png)

![Screenshot 2020-06-22 at 2 31 07 PM](https://user-images.githubusercontent.com/43811904/85378236-dd2c8800-b56c-11ea-9491-788e5d986276.png)
![Screenshot 2020-06-22 at 2 47 42 PM](https://user-images.githubusercontent.com/43811904/85378248-df8ee200-b56c-11ea-9beb-c5e3f05edf2c.png)
(In the training time, the hop_size, sample_rate and window_size were set as the same for the tacotron, WaveGlow and waveGan model.)

I successfully synthesized speech using WaveGan with espnet's FastSpeech, but I failed to use waveGan to synthsize intelligible voice with any model derived from Nivida's Tacotron2 implementation (e.g. Glow-TTS). Could you please give me any advice? 
(Because in Nivida's Tacotron2, there is no `cmvn` to the input mel-spectrogram features, so I didn't calculate the cmvn of the training waves and didn't invert it back at the inference time)

Thank you very much!

**Comment by kan-bayashi** [comment] 2020-06-24 02:11
Let me confirm some points:
- Did you check the range of Mel basis? We use 80-7600.
- Not sure but I use librosa to extract mel-spectrogram. Maybe Nvidia's extractor is different. This may cause the mismatch.
- In inference, how did you perform normalization? txt -> [Taco2] -> Mel -> ? -> [PWG]?

**Comment by Charlottecuc** [comment] 2020-06-24 05:00
Thank you for your reply.
- Yes. I checked the range Mel basis. It's 80-7600.

- Nvidia uses `scipy.io.wavfile.read` to read wave files and librosa is not used if `input_data.device.type == "cuda"`.(https://github.com/jaywalnut310/glow-tts/blob/00a482d06ebbffbd3518a43480cd79e7b47ebbe2/stft.py#L78)
![Screenshot 2020-06-24 at 12 48 54 PM](https://user-images.githubusercontent.com/43811904/85502097-381bb900-b619-11ea-85bc-b5125fb55171.png)
![Screenshot 2020-06-24 at 12 48 30 PM](https://user-images.githubusercontent.com/43811904/85502124-436ee480-b619-11ea-9fe3-983f1a86d83d.png)

- Since I used different datasets for Text2Mel and Mel2Wav models, I firstly read `stats.h5` of pretrained WaveGan and got `new_mean` and `new_square` from `stats.h5`. Then, `(Mel - new_mean) / new_square`
![Screenshot 2020-06-24 at 12 58 02 PM](https://user-images.githubusercontent.com/43811904/85502718-7e254c80-b61a-11ea-97b5-44ea34372166.png)
(`c` is the Mel from Taco2)

Thanks!

**Comment by kan-bayashi** [comment] 2020-06-24 07:00
I checked the following code.
https://github.com/jaywalnut310/glow-tts/blob/00a482d06ebbffbd3518a43480cd79e7b47ebbe2/commons.py#L164-L181
It seems that it does not apply log for mel-spectrogram and performs dynamic range compression.
Why don't you try the following procedure?

txt -> [Taco2] -> Mel -> [de-compression] -> [log10] -> [cmvn] -> [PWG]

**Comment by seantempesta** [comment] 2020-06-25 06:25
I'm having the same problem, but I don't understand the `[cmvn]` step you referenced above.  I tried de-compressing the mel and then applying log10, and I can kind of make out words in the audio, but it's super noisy.  Would you mind elaborating? 

Here's what I've got:

```python
from audio_processing import dynamic_range_decompression

# generate the MEL using Glow-TTS
with torch.no_grad():
    noise_scale = .667
    length_scale = 1.0
    (c, *r), attn_gen, *_ = model(x_tst, x_tst_lengths, gen=True, noise_scale=noise_scale, length_scale=length_scale)
   
# Decompress and log10 the output
decompressed = dynamic_range_decompression(c)
decompressed_log10 = np.log10(decompressed.cpu()).cuda()

# Run the PWG vocoder and play the output
with torch.no_grad():
    xx = (decompressed_log10,)
    y = pqmf.synthesis(vocoder(*xx)).view(-1)      
    
from IPython.display import display, Audio
display(Audio(y.view(-1).cpu().numpy(), rate=config["sampling_rate"]))
```

**Comment by kan-bayashi** [comment] 2020-06-25 06:45
`[cmvn]` means the mean-var normalization using `stats.h5` of PWG model.
In your case, 
```python
# load PWG statistics
mu = read_hdf5("/path/to/stats.h5", "mean")
var = read_hdf5("/path/to/stats.h5", "scale")
sigma = np.sqrt(var)

# mean-var normalization
decompressed_log10_norm = (decompressed_log10 - mu) / sigma

# then input to vocoder
...  
```

**Comment by seantempesta** [comment] 2020-06-25 07:41
@kan-bayashi  You are amazing! For anyone else running into this, you have to change the tensor shapes for `mu` and `var` to get this to work.  This is what I did (please let me know if this isn't right):

```python
from audio_processing import dynamic_range_decompression
from parallel_wavegan.utils import read_hdf5

# config
stats_path = '/path/to/stats.h5'

# generate the MEL using Glow-TTS
with torch.no_grad():
    noise_scale = .667
    length_scale = 1.0
    (c, *r), attn_gen, *_ = model(x_tst, x_tst_lengths, gen=True, noise_scale=noise_scale, length_scale=length_scale)
   
# Decompress and log10 the output
decompressed = dynamic_range_decompression(c)
decompressed_log10 = np.log10(decompressed.cpu()).cuda()

# mean-var normalization
mu = read_hdf5(stats_path, "mean")
var = read_hdf5(stats_path, "scale")
sigma = np.sqrt(var)
decompressed_log10_norm = (decompressed_log10 - torch.from_numpy(mu).view(1, -1, 1).cuda()) / torch.from_numpy(sigma).view(1, -1, 1).cuda()

# Run the PWG vocoder and play the output
with torch.no_grad():
    xx = (decompressed_log10,)
    y = pqmf.synthesis(vocoder(*xx)).view(-1)      
    
from IPython.display import display, Audio
display(Audio(y.view(-1).cpu().numpy(), rate=config["sampling_rate"]))
```

**Comment by kan-bayashi** [comment] 2020-06-25 08:23
@seantempesta Great!

**Comment by kan-bayashi** [comment] 2020-06-25 09:31
Now I can combine with Nividia's tacotron2-based models.
I will close this issue and write some note in README.

**Closed by kan-bayashi** 2020-06-25 09:31 UTC
Labels: question

**Comment by Charlottecuc** [comment] 2020-06-28 06:55
Hi @seantempesta. I copied your code and got the following error:
---------------------------------------------------------------------------
```
TypeError                                 Traceback (most recent call last)
<ipython-input-60-39f0bece3260> in <module>
     18 with torch.no_grad():
     19     xx = (decompressed_log10_norm,)
---> 20     y = pqmf.synthesis(vocoder(*xx)).view(-1)

/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    545             result = self._slow_forward(*input, **kwargs)
    546         else:
--> 547             result = self.forward(*input, **kwargs)
    548         for hook in self._forward_hooks.values():
    549             hook_result = hook(self, input, result)

TypeError: forward() missing 1 required positional argument: 'c'
```

Could you please give me some advice? Thanks!

**Comment by Charlottecuc** [comment] 2020-06-28 08:21
`with torch.no_grad():
# generate the MEL using Glow-TTS
  noise_scale = .667
  length_scale = 1.0
  (c, *r), attn_gen, *_ = model(x_tst, x_tst_lengths, gen=True, noise_scale=noise_scale, length_scale=length_scale)
  c_lengths = torch.tensor([c.shape[2]]).cuda()
  attn_gen = attn_gen.squeeze(0).squeeze(0)

#plot the MEL
  plot_data((c.float().data.cpu().numpy()[0],
           attn_gen.float().data.cpu().numpy()))
    
#Decompress and log10 the output
  c = dynamic_range_decompression(c)
  c = np.log10(c.cpu()).cuda()
  c = c.squeeze(0) 
  c = c.permute(1,0)

# mean-var normalization
  new_mean = read_hdf5(stats_path, "mean")
  new_square = read_hdf5(stats_path, "scale")
  sigma = np.sqrt(new_square)
  if is_cmvn:
    c = decompressed_log10.cpu().detach().numpy()
    c = (c - new_mean) / sigma
    c = torch.from_numpy(c).float()
    c = c.to(device)
    
# Run the PWG vocoder and play the output    
  x = ()
  z = torch.randn(1, 1, c_lengths * config["hop_size"]).to(device)
  x += (z,)
  c = pad_fn(c.unsqueeze(0).transpose(2, 1))
  print("c.size:", c.size())
  x += (c,)

  y = pqmf.synthesis(vocoder(*x)).view(-1)
  #y = y * 32768.0

from IPython.display import display, Audio
display(Audio(y.view(-1).cpu().numpy(), rate=22050))`

Here is my code, but the synthesized voice is like from a radio with poor signal:
![Screenshot 2020-06-28 at 4 20 31 PM](https://user-images.githubusercontent.com/43811904/85942370-59eba780-b95b-11ea-9744-344d6ff9c71b.png)
![Screenshot 2020-06-28 at 4 19 55 PM](https://user-images.githubusercontent.com/43811904/85942371-5ce69800-b95b-11ea-955c-829ba454bafd.png)

**Comment by kan-bayashi** [comment] 2020-06-28 09:04
@Charlottecuc There are three vocoder models in this repository, PWG, MelGAN, and multi-band MelGAN.
The input is different for each model:
- PWG: mel-spectrogram and noise
- MelGAN and multi-band MelGAN: mel-spectrogram.

And only the multi-band MelGAN needs PQMF filter as a post-processing to convert 4 ch signal into 1 ch signal.

@seantempesta used multi-band MelGAN, so the input is only `c` and `pqmf.synthesis` is applied.
In your @Charlottecuc case, you want to use PWG. So you do not need to use PQMF.
Please remove `pqmf.synthesis`.

**Comment by Charlottecuc** [comment] 2020-06-28 11:24
@kan-bayashi Great!!!!!Thank you for your advice.

**Comment by Charlottecuc** [comment] 2020-06-28 12:19
Hi @kan-bayashi One last question:
I successfully used MelGAN to synthezised beautiful voice in Mandarin, but when I turned to WaveGAN by using the same code above (`pqmf.synthesis` was removed), it seems that there is something wrong in the F0 of synthesized voice. That is, with the same Mel, MelGAN synthesized female's voice (which is right), and WaveGAN synthesized male's voice (which is quite strange). Could you give me some advice? Thank you very much!

**Comment by kan-bayashi** [comment] 2020-06-28 12:43
I've never met such a problem.
Maybe you made something wrong (e.g., sampling rate).

**Comment by Charlottecuc** [comment] 2020-07-01 02:49
Solved. Thank you :)

**Comment by ly1984** [comment] 2020-07-16 14:58
@seantempesta could you please share your complete inference code, I am not sure where x_tst, x_tst_lengths come from,much appreciated.

**Comment by ly1984** [comment] 2020-07-24 04:22
@kan-bayashi the inference voice with lots of noise, could you please take a look?
`%cd /tts/glow-tts/
%matplotlib inline
import matplotlib.pyplot as plt
import IPython.display as ipd

import sys
sys.path.append('/tts/ParallelWaveGAN/')
from audio_processing import dynamic_range_decompression
from parallel_wavegan.utils import read_hdf5

import librosa
import numpy as np
import os
import glob
import json
import soundfile as sf
import torch
from text import text_to_sequence, cmudict
from text.symbols import symbols
import commons
import attentions
import modules
import parallel_wavegan.models
import utils
import yaml
from parallel_wavegan.models import ParallelWaveGANGenerator
import time

model_dir = "/tts/glow-tts/model_dir/"
hps = utils.get_hparams_from_dir(model_dir)
model = models.FlowGenerator(
    len(symbols),
    out_channels=hps.data.n_mel_channels,
    **hps.model).to("cuda")

checkpoint_path = utils.latest_checkpoint_path(model_dir)
utils.load_checkpoint(checkpoint_path, model)
model.decoder.store_inverse() # do not calcuate jacobians for fast decoding
_ = model.eval()

cmu_dict = cmudict.CMUDict(hps.data.cmudict_path)

tst_stn = " In recent years , there is a heated debate on whether we should offer seats to elderly people on the bus during rush hours . As for such question , people's opinions vary from person to person . " # Adding spaces at the beginning and the end of utterance improves quality
sequence = np.array(text_to_sequence(tst_stn, ['english_cleaners'], cmu_dict))[None, :]
print("".join([symbols[c] for c in sequence[0]]))
x_tst = torch.autograd.Variable(torch.from_numpy(sequence)).cuda().long()
x_tst_lengths = torch.tensor([x_tst.shape[1]]).cuda()

stats_path = '/tts/glow-tts/mel_model/stats.h5'
vocoder_conf = "/tts/ParallelWaveGAN/egs/ljspeech/voc1/conf/melgan.v3.yaml"
vocoder_path = "/tts/glow-tts/mel_model/checkpoint-2000000steps.pkl"
device = torch.device("cuda")

with open(vocoder_conf) as f:
    config = yaml.load(f, Loader=yaml.Loader)
vocoder_class = config.get("generator_type", "ParallelWaveGANGenerator")
vocoder = getattr(parallel_wavegan.models, vocoder_class)(**config["generator_params"])
vocoder.load_state_dict(torch.load(vocoder_path, map_location="cpu")["model"]["generator"])
vocoder.remove_weight_norm()
vocoder = vocoder.eval().to(device)
if config["generator_params"]["out_channels"] > 1:
    from parallel_wavegan.layers import PQMF
    pqmf = PQMF(config["generator_params"]["out_channels"]).to(device)

pad_fn = torch.nn.ReplicationPad1d(
    config["generator_params"].get("aux_context_window", 0))
use_noise_input = vocoder_class == "ParallelWaveGANGenerator"

# generate the MEL using Glow-TTS
with torch.no_grad():
    noise_scale = .667
    length_scale = 1.0
    (c, *r), attn_gen, *_ = model(x_tst, x_tst_lengths, gen=True, noise_scale=noise_scale, length_scale=length_scale)
    
# Decompress and log10 the output
decompressed = dynamic_range_decompression(c)
decompressed_log10 = np.log10(decompressed.cpu()).cuda()

# mean-var normalization
mu = read_hdf5(stats_path, "mean")
var = read_hdf5(stats_path, "scale")
sigma = np.sqrt(var)
decompressed_log10_norm = (decompressed_log10 - torch.from_numpy(mu).view(1, -1, 1).cuda()) / torch.from_numpy(sigma).view(1, -1, 1).cuda()

if config["generator_params"]["out_channels"] > 1:
    from parallel_wavegan.layers import PQMF
    pqmf = PQMF(config["generator_params"]["out_channels"]).to(device)

# Run the PWG vocoder and play the output
with torch.no_grad():
    start = time.time()
    if use_noise_input:
        xx = (decompressed_log10_norm,)
    if config["generator_params"]["out_channels"] == 1:
        y = vocoder(*xx).view(-1)
        print("1111")
    else:
        y = pqmf.synthesis(vocoder(*xx)).view(-1) 
        print("2222")
    
rtf = (time.time() - start) / (len(y) / config["sampling_rate"])
print(f"RTF = {rtf:5f}")    
    
from IPython.display import display, Audio
display(Audio(y.view(-1).cpu().numpy(), rate=config["sampling_rate"]))
`

**Comment by kan-bayashi** [comment] 2020-07-24 04:32
@ly1984 Check the hyperparameters of mel-spectrogram extraction. Maybe you use different fmax and fmin.

**Comment by ly1984** [comment] 2020-07-24 04:46
I've found the WaveGAN  fmin: 80   fmax: 7600 and  Glow-TTS    "mel_fmin": 0.0, "mel_fmax": 8000.0,
should I retrain the glow-its model with the same parameter with WaveGAN?

**Comment by kan-bayashi** [comment] 2020-07-24 04:48
Yes. You need to retrain PWG or Glow-TTS.

**Comment by ZDisket** [comment] 2020-08-17 23:11
@kan-bayashi My [audio ](https://u.smutty.horse/lwonajxpvdz.wav)has a lot of noise even though I trained ([FastSpeech2](https://github.com/ming024/FastSpeech2)) with fmin 80 and fmax 7600 like my PWGAN model.
I used this code to infer:
```
def dopwgansynth(inc):
  decompressed = dynamic_range_decompression(inc)
  decompressed_log10 = np.log10(decompressed.cpu()).cuda()

  # mean-var normalization
  stats = np.load("stats.npy")
  mu = stats[0]
  var = stats[1]
  sigmaZ = np.sqrt(var)
  decompressed_log10_norm = (decompressed_log10 - torch.from_numpy(mu).view(1, -1, 1).cuda()) / torch.from_numpy(sigmaZ).view(1, -1, 1).cuda()
  c = pad_fn(decompressed_log10_norm).to(device)
  xx = (c,)
  if use_noise_input:
    z_size = (1, 1, (c.size(2) - sum(pad_fn.padding)) * config["hop_size"])
    z = torch.randn(z_size).to(device)
    xx = (z,) + xx

  y = vocoder(*xx).view(-1)
  return y   
```
Maybe I did something wrong with the `noise_input`? I couldn't unsqueeze nor transpose because I would get varying errors.
Just in case, this is the mel spectrogram.
![themel](https://user-images.githubusercontent.com/30500847/90452306-38d64600-e0c4-11ea-8c85-db6fd1bca34c.png)

**Comment by rijulg** [comment] 2020-08-19 12:44
@kan-bayashi I am trying to use your models with mel spectrogram output from Nvidia's models, and although the above suggested methods get some results, the results are rather lackluster. Here's a colab notebook of an experiment
https://colab.research.google.com/drive/1uOLIzWHF4FbRScuIeUQiMQyCE_zpphBe?usp=sharing
In the above experiment I have the same audio processed in following ways:

- audio -> pwgan_mel -> pwgan_inference (vctk_multi_band_melgan.v2) -> audio [OK]
- audio -> pwgan_mel -> pwgan_inference (libritts_parallel_wavegan.v1.long) -> audio [Good]
- audio -> tacotron2_mel -> pwgan_inference (libritts_parallel_wavegan.v1.long) -> audio [Terrible]
- audio -> tacotron2_mel -> mean-var normalization -> pwgan_inference (libritts_parallel_wavegan.v1.long) -> audio [Poor]

I observe the following from the experiment:
- vctk_multi_band_melgan.v2 trained model performs slightly worse than libritts_parallel_wavegan.v1.long on my selected audio.
- tacotron2_mel output does not work with the trained models, as expected
- tacotron2_mel output with mean-var normalization does not produce high quality outputs
- tacotron2_mel lengths are (1200/1024) times that of pwgan_mel (this is expected because of the window size difference)

Can you please comment on, and help me identify any problems with
1. Identifying cause of quality difference between the 2 trained models
    - I suspect it is a combination of the dataset used to train and the total steps involved in training
2. Reason for poor quality of tacotron2_mel even after mean-var normalization
    - I suspect that the conversion is not able to match up with the difference in fft_size and window_size

**Comment by kan-bayashi** [comment] 2020-08-19 12:51
@rijulg Did you check this comment?
https://github.com/kan-bayashi/ParallelWaveGAN/issues/169#issuecomment-649320778
The base of `log` is different, so you need to convert [taco2_mel] -> exp -> log10 -> mean-var norm.

**Comment by rijulg** [comment] 2020-08-19 13:00
@kan-bayashi yes, I am indeed doing the log base conversion; I guess I (mistakenly) considered the log conversion part of your mean-var normalization process so did not mention it separately.

**Comment by kan-bayashi** [comment] 2020-08-19 13:03
In your code, the range of mel-basis is different.
That is the reason of quality degradation.

**Comment by rijulg** [comment] 2020-08-19 13:08
Ah, alright. Just to confirm there is no way of scaling right? Leaving the only option of retraining the models?

**Comment by kan-bayashi** [comment] 2020-08-19 13:09
Unfortunately, you need to retrain :(

**Comment by Zarbuvit** [comment] 2020-10-01 13:36
@seantempesta I tried your fix for GlowTTS inference with multiband melgan using the Mozilla-TTS multiband melgan, and though it did take away the noisy background but it left me with garbled up words.
Did this ever happen to you?
I tried, and I would prefer, to use the multiband melgan model provided by kan-bayashi but I couldnt figure out how to load the model properly and kept running into tensor size incompatibility issues. If it is possible for you to share how you got `vocoder` from your inference line ` y = pqmf.synthesis(vocoder(*xx)).view(-1)` I would be very greatful - it will probably solve for me what I have had problems with for the past week.

**Comment by Zarbuvit** [comment] 2020-10-08 13:14
I ended up trying another method provided in the repo https://github.com/rishikksh20/melgan. I got the same garbled voice results.
I then realized that I had a personal mistake of mixing up my training and inference models and that was the cause for the garbling. Once I fixed this everything worked perfect!
This is all to say, I am not sure if this would have solved the garbling problem I had here, I didn't check, but I am almost certain that @seantempesta code did actually work for me and any problem I had was on my side of things.
I am sorry for any problems or wasted time I may have caused.

**Comment by lucashueda** [comment] 2020-11-23 05:32
Since the sound itself is not affected by a wav normalization (audio /= (1 << (16 -1)), is there a way to use a PWGAN trained without wav norm to synthetize tacotron2 model output trained with wav norm? 

Additionally, someone know if wav norm is needed to converge tacotron2? I tried without wav norm to match a internal PWGAN trained without wav norm, but tacotron2 run 30k steps without attention alignment.

**Comment by kan-bayashi** [comment] 2020-11-23 06:08
@lucashueda I did not understand ‘wav norm’ you mentioned. Did you use wav with the scale from -66536 to 66536?

**Comment by lucashueda** [comment] 2020-11-23 09:42
> @lucashueda I did not understand ‘wav norm’ you mentioned. Did you use wav with the scale from -66536 to 66536?

With "wav norm" I mean " audio /= (1 << (16-1)) " to make a 16bit PCM file between -1 and +1. But i realize that differente wav readers read these files differently, I was just confused with the "bin/preprocess.py" file where if I put the input_dir argument it just calls "load_wav" to read a wav file but if you pass a kaldi style file it performs the "wav norm", but as I saw the soundfile package already performs the normalization.

**Comment by kan-bayashi** [comment] 2020-11-23 10:18
Both cases will normalize the audio from -1 to 1.
The 'wav norm' is needed sicne `kaldiio` output is not normalized.

**Comment by wizardk** [comment] 2021-04-27 06:34
> `[cmvn]` means the mean-var normalization using `stats.h5` of PWG model.
> In your case,
> 
> ```python
> # load PWG statistics
> mu = read_hdf5("/path/to/stats.h5", "mean")
> var = read_hdf5("/path/to/stats.h5", "scale")
> sigma = np.sqrt(var)
> 
> # mean-var normalization
> decompressed_log10_norm = (decompressed_log10 - mu) / sigma
> 
> # then input to vocoder
> ...  
> ```

Hi @kan-bayashi , why do you need to do np.sqrt(var) ? In the compute_statistics.py, you have saved scale_ instead of var_.

**Comment by kan-bayashi** [comment] 2021-04-28 02:44
Oh, `scale` is std so we should use `scale` as `sigma` here.
