### ISSUE TITLE
> convert_melgan_from_pytorch_to_tensorflow (tf-lite conversion error)

### ISSUE THREAD

**Issue by John-K92** [kan-bayashi/ParallelWaveGAN#126] opened 2020-03-29 11:56 UTC
> what error ?

When I run the code, "audio = TFMelGANGenerator(**config["generator_params"])(inputs)" line raises an InaccessibleTensorError.

 InaccessibleTensorError: The tensor 'Tensor("conv2d_346/dilation_rate:0", shape=(2,), dtype=int32)' cannot be accessed here: it is defined in another function or code block. Use return values, explicit Python locals or TensorFlow collections to access it. Defined in: FuncGraph(name=call, id=140430667155440); accessed from: FuncGraph(name=call, id=140430364789896).

Do you not meet any error on your side?

_Originally posted by @John-K92 in https://github.com/kan-bayashi/ParallelWaveGAN/issues/61#issuecomment-604809032_

Any news on this colab??

**Comment by kan-bayashi** [comment] 2020-03-29 12:07
I reproduced this issue on colab.
The reason of this error seems the version of tensorflow (colab uses `2.2.0-rc0` now).
Please install `tensorflow-gpu==2.1` like this.
![D6055645-BB4C-465A-A583-B305D6AB2430](https://user-images.githubusercontent.com/22779813/77848651-3b153200-7201-11ea-9d32-2fb51de5ae6a.jpeg)

**Comment by John-K92** [comment] 2020-03-29 15:20
> I reproduced this issue on colab.
> The reason of this error seems the version of tensorflow (colab uses `2.2.0-rc0` now).
> Please install `tensorflow-gpu==2.1` like this.
> ![D6055645-BB4C-465A-A583-B305D6AB2430](https://user-images.githubusercontent.com/22779813/77848651-3b153200-7201-11ea-9d32-2fb51de5ae6a.jpeg)

Thank you for your support. re-installing tensorflow fixed the issue.
But may I ask you a question about converting the model to tf-lite model?
I have amended the cell #3 in the colab, to let input pass through the network. But I encountered another error in converting to tf-lite, the link is below. 
https://colab.research.google.com/drive/1ch7nkIzVx69Ol1ir-2LT2tXInXYBeavb

For some reason, the dimension does not match when converting and the error shows as "Check failed: dim_x == dim_y (2000 vs. 2006)Dimensions must match". Do you have any idea why it occurs?

**Comment by kan-bayashi** [comment] 2020-03-30 00:45
Actually, I'm not familiar with tensorflow, but your already shows the solution or hint.
```
2020-03-29 15:18:42.056310: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2020-03-29 15:18:42.056409: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2020-03-29 15:18:42.056425: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-03-29 15:18:43.046364: F tensorflow/lite/toco/graph_transformations/propagate_fixed_sizes.cc:118] Check failed: dim_x == dim_y (2000 vs. 2006)Dimensions must match
Fatal Python error: Aborted
```
It seems that the needed library is not installed.
At first, you should install related libraries such as `libnvinfer.so.6` and check the behavior again.

**Comment by dathudeptrai** [comment] 2020-03-30 02:03
@kan-bayashi @John-K92 :)))), i don't know how to say now :v. @John-K92  You should fix by yourselft in this case :))), i cann't share everything about how to convert it to tf-lite models ^^. Just modify some line of code u can convert it successfully, don't care about libninfer.so.6. The error is Check failed: dim_x == dim_y (2000 vs. 2006)Dimensions must match.

**Comment by kan-bayashi** [comment] 2020-03-30 03:28
OK. This issue is out of supports of this repository.
Please fix it by yourself. I will close this issue.
If you find the solution and share it, it is nice for the other users.

**Closed by kan-bayashi** 2020-03-30 03:28 UTC
Labels: bug
